[project]
name = "autorh247"
version = "0.1.0"
description = "Automação de Abono de Faltas e Integração de Ponto via API RH247"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.0",
    "pandas>=2.0.0",
    "requests>=2.31.0",
]

[project.scripts]
autorh247 = "autorh247.cli:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
